---
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: mavencrest-landing-zone/alz-mgmt-templates

parameters:
  - name: terraform_action
    displayName: Terraform Action to perform
    type: string
    default: 'apply'
    values:
      - 'apply'
      - 'destroy'
  - name: terraform_cli_version
    displayName: Terraform CLI Version
    type: string
    default: '1.14.9'

lockBehavior: sequential

extends:
  template: .pipelines/cd-template.yaml@templates
  parameters:
    terraform_action: ${{ parameters.terraform_action }}
    root_module_folder_relative_path: .
    terraform_cli_version: ${{ coalesce(parameters.terraform_cli_version, 'latest') }}
